package constants

var Skills = map[string]string{"Acrobatics": "Dex", "Arcana": "Int", "Athletics": "Str", "Crafting": "Int", "Deception": "Cha", "Diplomacy": "Cha", "Intimidation": "Cha", "Medicine": "Wis", "Nature": "Wis", "Occultism": "Int", "Performance": "Cha", "Religion": "Wis", "Society": "Int", "Stealth": "Dex", "Survival": "Wis", "Thievery": "Dex"}
var Abilities = map[string]string{"Str": "@{strength_modifier}", "Dex": "@{dexterity_modifier}", "Con": "@{constitution_modifier}", "Cha": "@{charisma_modifier}", "Int": "@{intelligence_modifier}", "Wis": "@{wisdom_modifier}"}

const SpellCritRoll = "{{roll03_name=^{critical_damage}}} {{roll03=[[([[@{damage_dice} + (@{damage_ability})[@{text_ability_modifier}] + (@{damage_misc})[@{text_misc}] + (@{damage_other})[@{text_other}] + (@{query_roll_damage_bonus})[@{text_roll_damage_bonus}]]])*2]]}} {{roll03_type=critical-damage}} {{roll03_info=@{damage_type}}} {{roll04_name=^{damage_additional}}} {{roll04=@{damage_additional}}} {{roll04_type=damage}}"
const SpellDmgRoll = "{{roll02misc=[^{roll} ^{damage}](~repeating_cantrip_DAMAGE) }}{{roll03misc=[^{roll} ^{critical_damage}](~repeating_cantrip_CRITICAL_DAMAGE) }}"
const SpellCritDmg = "{{roll03misc=[^{roll} ^{critical_damage}](~repeating_cantrip_CRITICAL_DAMAGE) }}"
const RangedWeaponRoll1 = "{{roll01_name=^{attack}}} {{roll01=[[1d20cs20cf1 + [@{weapon_proficiency_display}] @{weapon_strike}[@{text_modifier}] + (0)[OTHER] + (@{query_roll_bonus})[@{text_bonus}]]]}} {{roll01_type=attack}} {{roll01_info=@{weapon_traits}}} {{roll01_critical=1}}{{roll01misc=[^{attack} #2](~repeating_ranged-strikes_ATTACK-DAMAGE2) [^{attack} #3](~repeating_ranged-strikes_ATTACK-DAMAGE3) }}"
const RangedWeaponRoll2 = "{{roll01_name=^{attack #2}}} {{roll01=[[1d20cs20cf1 + [@{weapon_proficiency_display}] @{weapon_strike}[@{text_modifier}] + (@{strikes_map2})[MAP #2] + (0)[OTHER] + (@{query_roll_bonus})[@{text_bonus}]]]}} {{roll01_type=attack}} {{roll01_info=@{weapon_traits}}} {{roll01_critical=1}}{{roll01misc=[^{attack} #3](~repeating_ranged-strikes_ATTACK-DAMAGE3) }}"
const RangedWeaponRoll3 = "{{roll01_name=^{attack #3}}} {{roll01=[[1d20cs20cf1 + [@{weapon_proficiency_display}] @{weapon_strike}[@{text_modifier}] + (@{strikes_map3})[MAP #3] + (0)[OTHER] + (@{query_roll_bonus})[@{text_bonus}]]]}} {{roll01_type=attack}} {{roll01_info=@{weapon_traits}}} {{roll01_critical=1}}"
const RangedDamagedRoll = "{{roll02_name=^{damage}}} {{roll02=[[@{damage_dice_query}@{damage_dice_size} + (@{damage_ability})[@{text_ability_modifier}] + (@{damage_weapon_specialization})[WEAPON SPECIALIZATION] + (@{damage_temporary})[TEMP] + (0)[OTHER] + (@{query_roll_damage_bonus})[@{text_roll_damage_bonus}]]]}} {{roll02_type=damage}} {{roll02_info=@{damage_info}}}"
const RangedCritDamageRoll = "{{roll03_name=^{critical_damage}}} {{roll03=[[(@{critical_damage_dice_query}@{critical_damage_dice_size} + (@{damage_ability})[@{text_ability_modifier}] + (@{damage_weapon_specialization})[WEAPON SPECIALIZATION] + (@{damage_temporary})[TEMP] + (0)[OTHER] + (@{query_roll_damage_bonus})[@{text_roll_damage_bonus}])*2 + (0)[ADDITIONAL DAMAGE] ]]}} {{roll03_type=critical-damage}} {{roll03_info=@{damage_info}}} {{roll04_name=^{damage_additional}}} {{roll04=@{damage_additional}}} {{roll04_type=damage}}"
const RangedStrikeDamageRoll = "{{roll02misc=[^{roll} ^{damage}](~repeating_ranged-strikes_DAMAGE) }}{{roll03misc=[^{roll} ^{critical_damage}](~repeating_ranged-strikes_CRITICAL_DAMAGE) }}"
const RangedStrikeCritRoll = "{{roll03misc=[^{roll} ^{critical_damage}](~repeating_ranged-strikes_CRITICAL_DAMAGE) }}"
const PF2_API_KEY = "da468b89-2bf8-4e2b-a939-79c6e6ef25ce"
